language: r
cache: packages
dist: trusty
sudo: true
latex: false
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-format-3.9
      - unixodbc-dev
      - apt-transport-https
      - gnupg
warnings_are_errors: false
before_install:
  - chmod +x ./odbcinstall.sh
  - ./odbcinstall.sh
  - odbcinst -q -d
  - env | grep 'ODBC'
install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dep = T)'
  - R CMD build --no-build-vignettes --no-manual .
  - R CMD check --no-build-vignettes --no-manual  *tar.gz
  - Rscript -e 'devtools::install(pkg = ".")'
script:
  - ./buildpres.sh
