sudo: required

services:
  - docker

install:
  - docker build -t lockedata/pres-azure .

script:
  - docker run -e GITHUB_PAT -e TRAVIS_REPO_SLUG lockedata/pres-azure /bin/sh -c "./pres-azure/buildpres.sh"
