---
title: "Is the cloud cost effective?"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(dplyr)
library(shiny)
library(DT)
library(flexdashboard)
library(ggplot2)
library(ggthemes)
library(optiRum)
library(hrbrthemes)

createflow <- function(x, pos, len) {
  basis <- vector(mode = "numeric", len)
  basis[pos] <- x
  return(basis)
}

cashflows <- function(servercost = 35000,
                      licencecost = 40000,
                      onpremdevcost = 30000,
                      months = 36,
                      residualvalue=.1,
                      clouddevcost = 30000,
                      cloudcost = 1000,
                      cloudincreaserate = 0.02,
                      interestrate = 0.05 / 12) {
  startbalance <- servercost + licencecost + pmax(onpremdevcost,clouddevcost)
  monthdepreciation<-(1-residualvalue)/months
  t <- 0:months
  
  stub <- tibble::tibble(
    per=t,
    credit = 0,
    debit = 0,
    balance = startbalance,
    asset = 0,
    totalval = startbalance
  )
  
  
  stub %>%
    mutate(
      credit = createflow(startbalance, 1, months + 1),
      debit = createflow(-startbalance, 2, months + 1)
    ) %>%
    mutate(asset =  (t>0)*(1-t*monthdepreciation)*servercost ) %>%
    mutate(balance = cumsum(credit + debit))  %>%
    mutate(totalval = balance + asset) %>%
    mutate_if(is.double, round, digits = 2) ->
    onprem
  
  stub %>%
    mutate(credit = createflow(startbalance, 1, months + 1)) %>%
    mutate(debit = ifelse(per < 1, 0, -cloudcost * (1 + cloudincreaserate) ^ per - 1)) %>%
    mutate(debit=ifelse(per==1,debit-clouddevcost,debit)) %>% 
    mutate(credit = ifelse(per < 1, startbalance, cumsum(credit + debit) *
                             interestrate)) %>%
    mutate(balance = cumsum(credit + debit))  %>%
    mutate(totalval = balance + asset) %>%
    mutate_if(is.double, round, digits = 2) ->
    cloud
  
  return(list(onprem = onprem, cloud = cloud))
}
```


Parameters {.sidebar}
=====================================

```{r}
sliderInput(
  "server",
  "Server cost",
  4e4,
  min = 0,
  max = 1e6,
  step = 5e3
)
sliderInput(
  "licence",
  "Licence cost",
  4e4,
  min = 0,
  max = 1e6,
  step = 2e3
)

sliderInput(
  "onpremdev",
  "On-prem dev cost",
  2e4,
  min = 0,
  max = 1e6,
  step = 2e3
)
sliderInput(
  "time",
  "Server lifespan",
  36,
  min = 12,
  max = 120,
  step = 6
)
sliderInput(
  "finalval",
  "Residual value",
  .1,
  min = 0,
  max = 1,
  step = .01
)
sliderInput(
  "clouddevcost",
  "Cloud dev cost",
  4e4,
  min = 0,
  max = 1e6,
  step = 2e3
)
sliderInput(
  "cloud",
  "Starting cloud bill p/m",
  1e3,
  min = 0,
  max = 1e4,
  step = 1e1
)
sliderInput(
  "inc",
  "Estimated cost increase p/m",
  .02,
  min = 0,
  max = .5,
  step = .005
)
sliderInput(
  "int",
  "Investment interest rate p/m",
  .01,
  min = 0,
  max = .5,
  step = .005
)
```



```{r}
results <- reactive(
  cashflows(
    servercost = input$server,
    licencecost = input$licence,
    onpremdevcost = input$onpremdev,
    months=input$time,
    residualvalue = input$finalval,
    cloudcost = input$cloud,
    clouddevcost = input$clouddevcost,
    cloudincreaserate = input$inc,
    interestrate = input$int
  )
)

ub <- reactive((input$server + input$licence + pmax(input$onpremdev, input$clouddevcost)) * 1.05)
lb <- reactive(pmin(
  0,
  min(results()$onprem$totalval) * 1.05,
  min(results()$cloud$totalval) * 1.05
))
```


Overview
=====================================  

On-premises 
-----------------------------------------------------------------------
### On-prem

```{r}
renderPlot({
  ggplot(results()$onprem, aes(x = per, y = totalval)) +
    geom_line(size = 3, colour = "#2165B6") +
    scale_y_comma(limits = c(lb(), ub())) +
    hrbrthemes::theme_ipsum(
      base_size = 18,
      axis_title_size = 24,
      grid = FALSE,
      axis = FALSE
    ) +
    labs(x = "Months", y = "Balance + Assets",
         title = "The cost of buying a server over time") +
    geom_hline(aes(yintercept = 0), colour = "#E8830C") +
    geom_text(
      data = results()$onprem[input$time + 1, ],
      aes(y = totalval * .95, label = optiRum::thousands(totalval)),
      size = 12,
      colour = "#E8830C"
    )
})
```


Cloud
-----------------------------------------------------------------------
### Cloud
```{r}
renderPlot({
  ggplot(results()$cloud, aes(x = per, y = totalval)) +
    geom_line(size = 3, colour = "#2165B6") +
    scale_y_comma(limits = c(lb(), ub())) +
    hrbrthemes::theme_ipsum(
      base_size = 18,
      axis_title_size = 24,
      grid = FALSE,
      axis = FALSE
    ) +
    labs(x = "Months", y = "Balance + Assets",
         title = "The cost of using the cloud over time") +
    geom_hline(aes(yintercept = 0), colour = "#E8830C") +
    geom_text(
      data = results()$cloud[input$time + 1, ],
      aes(y = totalval * .95, label = optiRum::thousands(totalval)),
      size = 12,
      colour = "#E8830C"
    )
})
```


Data
=====================================  

### On-prem data
```{r}
renderDataTable(results()$onprem)
```

### Cloud data
```{r}
renderDataTable(results()$cloud)
```
